### PR TITLE
add google maps links to events with Locations

### LINKED ISSUE #46: Link to OpenStreetMap
#### https://welcome.openstreetmap.org/why-openstreetmap/

- published under an open license
- data hosted by OSM
- [API for downloading map data ](https://wiki.openstreetmap.org/wiki/Downloading_data#Construct_a_URL_for_the_HTTP_API)

### PR DESCRIPTION
**Pull request by gtmanfred**
Closes #46

This also removes pipenv

### CODE REVIEW

**Comment by WritingPanda** [comment]
That's interesting. Why did you decide to remove `pipenv` from the project? Is it because it is easier to use `pip`, and the added security benefit of `pipenv` did not add much value to the overall project?

**Comment by andrewthetechie** [comment]
How will this handle virtual events?

**Comment by gtmanfred** [comment]
Pipenv is just an extra layer that doesn't really add anything for us

**Comment by gtmanfred** [comment]
As for handling virtual events, let me modify the map to just spit out a link, and if location starts with http, i will spit out a link with just that, so we can link zooms or jitsi, and if it isn't we will pass it to google maps.

**Pull request merged**
